#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )         cygwin=true;;
  Darwin* )         darwin=true;;
  MSYS* | MINGW* )  msys=true;;
  NonStop* )        nonstop=true;;
esac

# -------------------------------------------------------------------------
# DeepEye Music Pro: Auto-detect compatible JDK
# Gradle 8.x bundled Kotlin cannot parse Java version strings from JDK 25+.
# Prefer JDK 21 or 17 if the default Java version is too new.
# -------------------------------------------------------------------------
resolve_java_home() {
    # If JAVA_HOME is already explicitly set and valid, use it
    if [ -n "$JAVA_HOME" ] ; then
        if [ -x "$JAVA_HOME/bin/java" ] ; then
            return 0
        fi
    fi

    # Check what the default java version is
    DEFAULT_JAVA_VER=$(java -version 2>&1 | head -1 | sed 's/.*version "\([0-9]*\)\..*/\1/')
    
    # If not a number (e.g., "1.8" style), extract properly
    case "$DEFAULT_JAVA_VER" in
        ''|*[!0-9]*) DEFAULT_JAVA_VER="" ;;
    esac

    # If default Java is fine (<= 22), use it
    if [ -n "$DEFAULT_JAVA_VER" ] && [ "$DEFAULT_JAVA_VER" -le 22 ] 2>/dev/null; then
        return 0
    fi

    # Default Java is too new (23+) or unavailable — look for JDK 21
    for CANDIDATE in \
        "/usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home" \
        "/usr/local/Cellar/openjdk@21"/*/libexec/openjdk.jdk/Contents/Home \
        "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home" \
        "/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home" \
        "/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home" \
        "/usr/lib/jvm/java-21-openjdk" \
        "/usr/lib/jvm/java-21-oracle" \
        "/usr/lib/jvm/java-21" \
        ; do
        if [ -x "$CANDIDATE/bin/java" ]; then
            echo "Auto-detected JDK 21 at: $CANDIDATE" >&2
            JAVA_HOME="$CANDIDATE"
            export JAVA_HOME
            return 0
        fi
    done

    # No compatible JDK found; proceed with default (will likely fail)
    warn "WARNING: Your default Java version ($(java -version 2>&1 | head -1)) may be incompatible with Gradle. Install JDK 21 if builds fail."
    return 0
}

resolve_java_home
# -------------------------------------------------------------------------

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    fi
fi

# Resolve links
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/$link"
    fi
done
SAVED="$(pwd)"
cd "$(dirname "$PRG")/" >/dev/null
APP_HOME="$(pwd -P)"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Collect all arguments for the java command
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"

exec "$JAVACMD" "$@"