# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in the Android SDK proguard file.

# Keep DSP engine classes (reflection-based AudioEffect instantiation)
-keep class com.deepeye.musicpro.dsp.engine.** { *; }

# Room
-keep class * extends androidx.room.RoomDatabase { *; }

# Hilt
-keep class dagger.hilt.** { *; }
-keep class javax.inject.** { *; }
-keep class * extends dagger.hilt.android.internal.managers.** { *; }

# Media3
-keep class androidx.media3.** { *; }

# Gson
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.deepeye.musicpro.domain.model.** { *; }
-keep class com.deepeye.musicpro.dsp.model.** { *; }

# Coroutines
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}

# OkHttp / Okio
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

-keep class com.deepeye.musicpro.data.source.remote.youtube.** { *; }

# Coil 3 rules live in the Project Omega section below.

# ── Project Omega: Release Hardening ──

# JNI / native bridges
# R8 cannot see a call site that lives in C++, so any `external fun` would lose its
# name and its owning class at link time (UnsatisfiedLinkError at first call).
# -keepclasseswithmembernames keeps the class name AND the native method names.
# Verified: this module currently declares no `external fun` and ships no
# jniLibs/.so, so this rule is preventative — it is a no-op today and correct the
# moment a native bridge is introduced.
-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}
-keep class * { @native <methods>; }
# Do not let R8 rename classes a System.loadLibrary("...") lookup depends on.
-keepclasseswithmembernames class * {
    public native *** nativeInit(...);
}

# Room
# The existing `-keep class * extends RoomDatabase` above only protects the
# database subclass. Room additionally reflects over every @Entity and @Dao type
# at open() time, so members must survive too. (No FTS4/FTS5 table exists in this
# project today, so no FTS-specific rule is warranted.)
-keep class com.deepeye.musicpro.data.** { *; }
-keep class com.deepeye.musicpro.dsp.data.** { *; }
-keep @androidx.room.Entity class * { *; }
-keep @androidx.room.Dao class * { *; }

# Hilt / Dagger
# dagger.hilt ships its own consumer rules; these pin the entry points the
# annotation processor generates so an incremental R8 run cannot drop them.
-keep @dagger.hilt.android.HiltAndroidApp class * { *; }
-keep class * extends dagger.hilt.android.internal.managers.** { *; }
-keep class dagger.hilt.** { *; }
-keep class javax.inject.** { *; }

# Gson (this project serialises with Gson, NOT kotlinx.serialization —
# verified: no @Serializable usage and no serialization Gradle plugin)
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.deepeye.musicpro.domain.model.** { *; }
-keep class com.deepeye.musicpro.dsp.model.** { *; }
-keepclassmembers,allowobfuscation class * {
    @com.google.gson.annotations.SerializedName <fields>;
}
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken

# Coroutines: internal service-loader classes are instantiated by name.
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}

# ── Runtime-safety backstops ──
# Enum valueOf/values() are called reflectively in places (DSP band routing,
# DataStore preferences); keep them so R8 cannot rewrite the constant pool.
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# Media3 sessions resolve receivers/activities by component name.
-keep class androidx.media3.** { *; }
-dontwarn androidx.media3.**

# Compose keeps its own metadata; do not strip the runtime annotations it
# reads for stability inference.
-keep @androidx.compose.runtime.Immutable class * { *; }
-keep @androidx.compose.runtime.Stable class * { *; }

# Coil
# This project is on Coil 3 (package `coil3.*`), NOT the Coil 2 `coil.*` package.
-keep class coil3.** { *; }
-dontwarn coil3.**

# ── Project Omega: R8 missing-class resolutions ──
# Generated by AGP at app/build/outputs/mapping/release/missing_rules.txt.
#
# coil3.PlatformContext: a genuine upstream Coil 3.0.4 packaging defect — the
# JVM artifact coil-network-okhttp references coil3.PlatformContext, but no
# 3.0.4 Android artifact (coil-core/coil-network-core .aar) actually ships it.
# Verified by scanning every io.coil-kt.coil3 archive in the Gradle cache: the
# class is absent from all of them, so it can never be resolved on-device and the
# reference (a lambda inside Coil's own OkHttp fetcher factory) is dead weight.
-keep class coil3.network.okhttp.OkHttpNetworkFetcherFactory$* { *; }
-dontwarn coil3.PlatformContext

# Optional / transitive dependencies that are referenced but never bundled.
# These are never loaded on Android, so warning about them is noise.
-dontwarn com.google.api.client.http.**
-dontwarn java.lang.management.**
-dontwarn jdk.dynalink.**
-dontwarn org.joda.time.**

# ── Pre-existing project rules (retained) ──

# Haze (glassmorphism blur library)
-keep class dev.chrisbanes.haze.** { *; }
-dontwarn dev.chrisbanes.haze.**

# DataStore Preferences
-keep class androidx.datastore.** { *; }
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite { *; }

# Paging 3
-keep class androidx.paging.** { *; }

# Recommendation models (Gson serialization via CacheManager)
-keep class com.deepeye.musicpro.domain.recommendation.** { *; }

# Palette (album art color extraction)
-keep class androidx.palette.** { *; }

-dontwarn com.google.re2j.**
-dontwarn java.beans.**
-dontwarn javax.script.**

# AEOS Vibe-Coding Phase 4: Preserve Control/Data plane structures and mesh contracts
-keep class com.deepeye.musicpro.aeos.mesh.** { *; }
-keep class com.deepeye.musicpro.aeos.data_plane.** { *; }
-keep class com.deepeye.musicpro.aeos.control_plane.** { *; }

